export const mockSearchData = [
  { id: 1, label: "808 Bass" },
  { id: 2, label: "Analog Synth Pack" },
  { id: 3, label: "Acoustic Guitar" },
  { id: 4, label: "Trap Drums Kit" },
  { id: 5, label: "Piano VST" },
  { id: 6, label: "Vinyl Crackle FX" },
  { id: 7, label: "Electric Bass" },
  { id: 8, label: "Lo-Fi Essentials" },
  { id: 9, label: "Orchestra Strings" },
  { id: 10, label: "Deep House Pack" },
  { id: 11, label: "Rhodes Piano" },
  { id: 12, label: "Drum Machine Kit" },
  { id: 13, label: "Ambient Textures" },
  { id: 14, label: "Saxophone Sample" },
  { id: 15, label: "Tech House Loops" },
  { id: 16, label: "Synthesizer Lead" },
  { id: 17, label: "Hip Hop Drums" },
  { id: 18, label: "Electric Guitar" },
  { id: 19, label: "Latin Percussion" },
  { id: 20, label: "Future Bass Pack" },
  { id: 21, label: "Trumpet Sample" },
  { id: 22, label: "Dubstep Bass" },
  { id: 23, label: "Analog Drum Kit" },
  { id: 24, label: "Cinematic FX" },
  { id: 25, label: "Vocal Chops" },
  { id: 26, label: "Jazz Piano" },
  { id: 27, label: "Bass House Pack" },
  { id: 28, label: "Flute Sample" },
  { id: 29, label: "Trap Melodies" },
  { id: 30, label: "EDM Leads" },
  { id: 31, label: "Orchestral Hits" },
  { id: 32, label: "R&B Essentials" },
  { id: 33, label: "Melodic Loops" },
  { id: 34, label: "Vintage Drums" },
  { id: 35, label: "Chill Wave Pack" },
  { id: 36, label: "Brass Section" },
  { id: 37, label: "Electronic Drums" },
  { id: 38, label: "String Ensemble" },
  { id: 39, label: "Techno Loops" },
  { id: 40, label: "Bass Guitar" },
  { id: 41, label: "World Percussion" },
  { id: 42, label: "Pop Vocals" },
  { id: 43, label: "Synth Wave Pack" },
  { id: 44, label: "Classical Piano" },
  { id: 45, label: "House Drums" },
  { id: 46, label: "Vinyl Samples" },
  { id: 47, label: "Digital Synths" },
  { id: 48, label: "Acoustic Drums" },
  { id: 49, label: "FX Pack" },
  { id: 50, label: "Breakbeat Kit" },
];
